version: "3.7"

services:
  vpn-client:
    build: .
    container_name: vpn-client
    restart: always
    cap_add:
      - NET_ADMIN
    network_mode: host
    devices:
      - /dev/net/tun
    labels:
      - nuvlaedge.component=True
      - nuvlaedge.deployment=production
